apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
  labels:
    app: $APP_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      imagePullSecrets:
        - name: aws-registry-key
      replicase: 3
      containers:
        - name: $APP_NAME
          image: $DOCKER_REPO:$IMAGE_NAME
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          livenessProbe:
            httpGet:
              path: /health-check
              port: 8090
            initialDelaySeconds: 3 # Tells kublet to wait for 3 seconds before preforming the first liveness check
            periodSeconds: 3 #Every 3 seconds the kublet need to perform liveness check
            failureThreshold: 2
