---
apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME
spec:
  selector:
    app: $APP_NAME
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: service-ingress
  annotations:  
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
  - hosts:
    - helloworld.myapp.com
    secretName: letsencrypt-staging
  rules:
  - host: $APP_NAME.com
    http:
      paths:
      - backend:
          serviceName: $APP_NAME
          servicePort: 80